In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,4,3,2]

In [3]:
np.array(l)   # return int data, not converted to str

array([1, 2, 3, 4, 5, 4, 3, 2])

In [4]:
l1 = [1,2,3,2,1,'susant', 33.33, True]

In [7]:
a1 = np.array(l1)  # return str data, converted to str

In [8]:
a1

array(['1', '2', '3', '2', '1', 'susant', '33.33', 'True'], dtype='<U32')

In [9]:
a2 = np.array([[2,3,4,5],[3,4,5,6]])  # 2d array

In [10]:
a2

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [13]:
a3 = np.array([[[1,2,3,4],[2,3,4,2],[4,5,6,7]]])  # 3d array

In [14]:
a3

array([[[1, 2, 3, 4],
        [2, 3, 4, 2],
        [4, 5, 6, 7]]])

In [15]:
a1.ndim

1

In [16]:
a2.ndim

2

In [17]:
a3.ndim

3

In [18]:
a1.size  # return total number of elements 

8

In [19]:
a2.size

8

In [20]:
a3.size

12

In [21]:
a1.shape   # tottal number of elements

(8,)

In [22]:
a2.shape  # 2 rows and 4 columns

(2, 4)

In [23]:
a3.shape   # 1 matrix, 3 rows , 4 columns

(1, 3, 4)

In [34]:
np.random.randint(1000,2220)  
# generate 4 digit number betwen the range 1000-2220

1123

In [35]:
np.random.randint(1,10)  
# generate random number between 1 to 10

4

In [36]:
np.random.randint(1,50,(10,3))  
# generate random numbers in between 1 to 50 in an array which has 10 rows and 3 columns and 1 matrix

array([[ 4,  8, 32],
       [42,  1, 45],
       [37, 17, 49],
       [36, 31, 34],
       [41, 38, 37],
       [40, 22, 15],
       [34, 46,  7],
       [ 8, 18,  7],
       [40, 12, 34],
       [41, 10,  1]])

In [37]:
np.random.randint(1,50,(2,10,3)) 
# generate random numbers in between 1 to 50 in an array which has 10 rows and 3 columns and  2 matrix

array([[[35, 23, 20],
        [18, 43,  6],
        [ 1,  8, 19],
        [ 7, 47, 10],
        [16, 48, 21],
        [ 9,  4, 18],
        [39, 19, 26],
        [ 8, 25, 39],
        [32,  6, 29],
        [14, 30, 13]],

       [[45, 13, 18],
        [28, 24,  6],
        [39, 29, 34],
        [ 3,  7, 31],
        [17, 49,  6],
        [ 2, 24, 27],
        [39, 48,  1],
        [ 9, 26, 46],
        [ 5,  8, 33],
        [23,  8,  7]]])

In [50]:
np.random.rand(5,2)  
# rand() generate random normal distribution which has here 5 rows and 2 colms

array([[0.45636703, 0.36033449],
       [0.76240865, 0.72470721],
       [0.72874278, 0.36090535],
       [0.02780406, 0.5662966 ],
       [0.5409436 , 0.16615736]])

In [54]:
np.random.randn(3,4)  
# randint -> generate int number but randn -> generate normal distribution, mean=0, standard deviation=1

array([[ 1.18823765, -0.44737593,  1.43145579, -1.65224501],
       [ 1.51137557, -3.43596529, -0.05752992,  0.31154839],
       [ 0.62988106, -1.5010766 , -1.26504294,  0.13030206]])

In [57]:
a4 = np.random.randn(4,4)

In [58]:
a4

array([[-0.36486092, -0.10705058, -0.49517509, -1.63297839],
       [-1.2454858 , -1.26767881,  1.08315568,  0.22291727],
       [-0.96611135,  0.28068799,  1.16642399,  0.4304751 ],
       [ 0.49710306,  1.40305999, -1.61556496, -0.89656584]])

In [60]:
a4.reshape(8,2)  
# reshape() - To reshape the array 4*4, 2*8, 8*2, 1*16

array([[-0.36486092, -0.10705058],
       [-0.49517509, -1.63297839],
       [-1.2454858 , -1.26767881],
       [ 1.08315568,  0.22291727],
       [-0.96611135,  0.28068799],
       [ 1.16642399,  0.4304751 ],
       [ 0.49710306,  1.40305999],
       [-1.61556496, -0.89656584]])

In [67]:
a4.reshape(8,-1345)   # reshape 8*2 , it takes 2 bydefault, -1345 is for negetive number

array([[-0.36486092, -0.10705058],
       [-0.49517509, -1.63297839],
       [-1.2454858 , -1.26767881],
       [ 1.08315568,  0.22291727],
       [-0.96611135,  0.28068799],
       [ 1.16642399,  0.4304751 ],
       [ 0.49710306,  1.40305999],
       [-1.61556496, -0.89656584]])

In [70]:
a4.reshape(2,2,4)  # 2 matrix * 2 rows * 4 columns 

array([[[-0.36486092, -0.10705058, -0.49517509, -1.63297839],
        [-1.2454858 , -1.26767881,  1.08315568,  0.22291727]],

       [[-0.96611135,  0.28068799,  1.16642399,  0.4304751 ],
        [ 0.49710306,  1.40305999, -1.61556496, -0.89656584]]])

In [71]:
a4.reshape(1,1,1,1,2,2,4)

array([[[[[[[-0.36486092, -0.10705058, -0.49517509, -1.63297839],
            [-1.2454858 , -1.26767881,  1.08315568,  0.22291727]],

           [[-0.96611135,  0.28068799,  1.16642399,  0.4304751 ],
            [ 0.49710306,  1.40305999, -1.61556496, -0.89656584]]]]]]])

In [72]:
a4

array([[-0.36486092, -0.10705058, -0.49517509, -1.63297839],
       [-1.2454858 , -1.26767881,  1.08315568,  0.22291727],
       [-0.96611135,  0.28068799,  1.16642399,  0.4304751 ],
       [ 0.49710306,  1.40305999, -1.61556496, -0.89656584]])

In [73]:
a4[0]  # retrive 0th index/rows data

array([-0.36486092, -0.10705058, -0.49517509, -1.63297839])

In [74]:
a4[1]  # retrive 1st index/rows data

array([-1.2454858 , -1.26767881,  1.08315568,  0.22291727])

In [77]:
a1

array(['1', '2', '3', '2', '1', 'susant', '33.33', 'True'], dtype='<U32')

In [75]:
a1[0]

'1'

In [76]:
a1[2:4]

array(['3', '2'], dtype='<U32')

In [79]:
a1[2:8:2]

array(['3', '1', '33.33'], dtype='<U32')

In [80]:
a2

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [81]:
a2[0]

array([2, 3, 4, 5])

In [82]:
a2[1]

array([3, 4, 5, 6])

In [83]:
a2[:,2:]

array([[4, 5],
       [5, 6]])

In [85]:
a2[0:2,2:4]

array([[4, 5],
       [5, 6]])

In [86]:
a5 = np.random.randint(2,90,(6,5))
# random numbers between 2 to 90 and rows =6, colmns =5

In [87]:
a5

array([[55, 31, 73, 84,  4],
       [35, 49, 62, 16, 46],
       [18, 61, 38, 22, 17],
       [32,  6, 72, 65, 39],
       [56,  7, 31, 45, 60],
       [45,  5, 73, 86, 23]])

In [88]:
a5[a5>40]  # filter operation

array([55, 73, 84, 49, 62, 46, 61, 72, 65, 56, 45, 60, 45, 73, 86])

In [89]:
a5

array([[55, 31, 73, 84,  4],
       [35, 49, 62, 16, 46],
       [18, 61, 38, 22, 17],
       [32,  6, 72, 65, 39],
       [56,  7, 31, 45, 60],
       [45,  5, 73, 86, 23]])

In [90]:
a5[0,0] = 100  # value assignment 

In [91]:
a5

array([[100,  31,  73,  84,   4],
       [ 35,  49,  62,  16,  46],
       [ 18,  61,  38,  22,  17],
       [ 32,   6,  72,  65,  39],
       [ 56,   7,  31,  45,  60],
       [ 45,   5,  73,  86,  23]])

In [92]:
a5[1,2]=300  # value assignment 

In [93]:
a5

array([[100,  31,  73,  84,   4],
       [ 35,  49, 300,  16,  46],
       [ 18,  61,  38,  22,  17],
       [ 32,   6,  72,  65,  39],
       [ 56,   7,  31,  45,  60],
       [ 45,   5,  73,  86,  23]])

In [96]:
a6 = np.random.randint(0,3,(3,3))
a6

array([[0, 0, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [97]:
a7 = np.random.randint(0,3,(3,3))
a7

array([[2, 2, 0],
       [1, 1, 0],
       [0, 1, 0]])

In [98]:
a6*a7  # element wise multiplication

array([[0, 0, 0],
       [2, 1, 0],
       [0, 1, 0]])

In [ ]:
# how to do matrix multiplication 
# criteria = 1st matrix's columns number and 2nd matrix's rows number should be same 
# for matrix multiplication we use @ for mutiply

In [99]:
a6@a7  # matrix multiplication

array([[0, 2, 0],
       [5, 7, 0],
       [5, 6, 0]])

In [100]:
a8 = np.random.randint(1,4,(2,3))
a8

array([[1, 1, 1],
       [2, 1, 2]])

In [101]:
a9 = np.random.randint(1,5,(3,2))
a9

array([[2, 1],
       [4, 1],
       [3, 3]])

In [102]:
a8@a9  # matrix multiplication

array([[ 9,  5],
       [14,  9]])

In [103]:
a8+100 # addition

array([[101, 101, 101],
       [102, 101, 102]])

In [104]:
a8*2  # multiplication

array([[2, 2, 2],
       [4, 2, 4]])

In [106]:
a8/0  # not return error, it returns infinite

C:\Users\dell\AppData\Local\Temp/ipykernel_3984/892560483.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a8/0  # not return error, it returns infinite,


array([[inf, inf, inf],
       [inf, inf, inf]])

In [107]:
a8**3  # power

array([[1, 1, 1],
       [8, 1, 8]], dtype=int32)

In [109]:
a10 = np.zeros((4,4))
a10

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [111]:
a11 = np.ones((4,5))
a11

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [112]:
# broadcast operation - rows wise and column wise operation like +, *, -

In [113]:
a11 + np.array([1,2,3,4,5])  # adding these element to each rows - row wise operation

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [115]:
a11 + np.array([[1,2,3,4]]).T  
# Transpose menas row will change to columns and viceversa, column wise aaddition

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [116]:
a6

array([[0, 0, 2],
       [2, 1, 2],
       [2, 1, 1]])

In [117]:
a6.T  # transpose -chage rows to columns and viceversa

array([[0, 2, 2],
       [0, 1, 1],
       [2, 2, 1]])

In [118]:
np.sqrt(a5)  # squart root operation

array([[10.        ,  5.56776436,  8.54400375,  9.16515139,  2.        ],
       [ 5.91607978,  7.        , 17.32050808,  4.        ,  6.78232998],
       [ 4.24264069,  7.81024968,  6.164414  ,  4.69041576,  4.12310563],
       [ 5.65685425,  2.44948974,  8.48528137,  8.06225775,  6.244998  ],
       [ 7.48331477,  2.64575131,  5.56776436,  6.70820393,  7.74596669],
       [ 6.70820393,  2.23606798,  8.54400375,  9.2736185 ,  4.79583152]])

In [120]:
np.exp(a5)  # exponential operation

array([[2.68811714e+043, 2.90488497e+013, 5.05239363e+031,
        3.02507732e+036, 5.45981500e+001],
       [1.58601345e+015, 1.90734657e+021, 1.94242640e+130,
        8.88611052e+006, 9.49611942e+019],
       [6.56599691e+007, 3.10429794e+026, 3.18559318e+016,
        3.58491285e+009, 2.41549528e+007],
       [7.89629602e+013, 4.03428793e+002, 1.85867175e+031,
        1.69488924e+028, 8.65934004e+016],
       [2.09165950e+024, 1.09663316e+003, 2.90488497e+013,
        3.49342711e+019, 1.14200739e+026],
       [3.49342711e+019, 1.48413159e+002, 5.05239363e+031,
        2.23524660e+037, 9.74480345e+009]])

In [121]:
np.log10(a5)

array([[2.        , 1.49136169, 1.86332286, 1.92427929, 0.60205999],
       [1.54406804, 1.69019608, 2.47712125, 1.20411998, 1.66275783],
       [1.25527251, 1.78532984, 1.5797836 , 1.34242268, 1.23044892],
       [1.50514998, 0.77815125, 1.8573325 , 1.81291336, 1.59106461],
       [1.74818803, 0.84509804, 1.49136169, 1.65321251, 1.77815125],
       [1.65321251, 0.69897   , 1.86332286, 1.93449845, 1.36172784]])

In [122]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [123]:
list(range(0,20,2)) # step = 2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [124]:
list(range(0,20,2.5)) 
# not work with step 2.5, for this we use arange

TypeError: 'float' object cannot be interpreted as an integer

In [125]:
np.arange(0,20,2.5)  # step 2.5 will work with arange

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

In [126]:
np.arange(1.5, 20.5, 2.5)  
# we can take start point, end point, step size as floating number 

array([ 1.5,  4. ,  6.5,  9. , 11.5, 14. , 16.5, 19. ])

In [127]:
np.linspace(2,3,num=50) 
# it generate 50 numbers in between 2 to 3 
# what is the step size between each element ?

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [128]:
# what is the step size between each element ? 
np.linspace(2,3,num=4,retstep=True)
#step sie =0.3333333333333333

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

In [130]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [131]:
# identity matrix which menas rows ==columns
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])